import type { GenerativeMotionPlan, MotionOperation } from "./generative-motion-plan";

/** Lab で調整済みの右向き走行サイクル operations（human-runner-right 用） */
export const RUN_RIGHT_OPERATIONS: MotionOperation[] = [
  {
    type: "pathMovement",
    target: "human.body",
    path: "jitter",
    amplitude: 2,
    role: "anticipation",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 0, down: 1.2, pass: 0, up: 1.2 },
  },
  {
    type: "rotation",
    target: "human.body",
    degrees: 16,
    origin: "hip",
    role: "anticipation",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 16, down: 16, pass: 16, up: 16 },
  },
  {
    type: "rotation",
    target: "human.head",
    degrees: 4,
    origin: "neck",
    role: "reaction",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: -2, down: 0, pass: -2, up: 0 },
  },
  {
    type: "rotation",
    target: "human.rightLeg",
    degrees: 45,
    origin: "hip",
    role: "action",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: -45, down: -15, pass: 55, up: -25 },
  },
  {
    type: "rotation",
    target: "human.rightLeg",
    degrees: 90,
    origin: "custom",
    role: "effect",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 15, down: 45, pass: 55, up: 90 },
  },
  {
    type: "rotation",
    target: "human.leftLeg",
    degrees: 45,
    origin: "hip",
    role: "action",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 45, down: -25, pass: -88, up: -15 },
  },
  {
    type: "rotation",
    target: "human.leftLeg",
    degrees: 90,
    origin: "custom",
    role: "effect",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 25, down: 90, pass: 0, up: 45 },
  },
  {
    type: "rotation",
    target: "human.leftArm",
    degrees: 55,
    origin: "shoulder",
    role: "action",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: -50, down: 0, pass: 85, up: 0 },
  },
  {
    type: "rotation",
    target: "human.leftArm",
    degrees: 45,
    origin: "custom",
    role: "effect",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: -35, down: -45, pass: -20, up: -45 },
  },
  {
    type: "rotation",
    target: "human.rightArm",
    degrees: 55,
    origin: "shoulder",
    role: "action",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: 50, down: 0, pass: -85, up: 0 },
  },
  {
    type: "rotation",
    target: "human.rightArm",
    degrees: 45,
    origin: "custom",
    role: "effect",
    timing: { start: 0, duration: 1 },
    repeat: "loop",
    easing: "linear",
    keyframes: { contact: -20, down: -45, pass: -35, up: -45 },
  },
];

export function buildRunRightMotionTemplate(
  predicate: string,
  sourceName?: string,
  targetName?: string,
): Pick<
  GenerativeMotionPlan,
  "asset" | "recipe" | "playback" | "semantic" | "participants"
> {
  return {
    semantic: {
      cdtCategory: "MOVE",
      predicate,
      intent: `${sourceName ?? "actor"} runs toward ${targetName ?? "target"}`,
      confidence: 0.9,
    },
    participants: {
      sourceRole: "actor",
      targetRole: "destination",
      primaryTarget: "source",
      direction: "sourceToTarget",
    },
    asset: {
      kind: "human",
      assetId: "human-runner-right",
      requiredParts: [
        "human.body",
        "human.head",
        "human.leftArm",
        "human.rightArm",
        "human.leftLeg",
        "human.rightLeg",
      ],
    },
    recipe: {
      preset: "bodyPartMotion",
      operations: RUN_RIGHT_OPERATIONS.map((op) => ({ ...op })),
    },
    playback: {
      durationMs: 600,
      delayMs: 0,
      loop: true,
      yoyo: false,
      easing: "linear",
      intensity: 1,
    },
  };
}
